wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    code_path: code/src/train_random_forest/run.py
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1707940801.278979
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.13.9
      8:
      - 5
